Repository MPS-FGA/Avaleasy-app, pull requests merged in 2018-10, with the labels that each got.

#26 Adicionado conexão entre as páginas
  App.js
  package.json
  src/components/FloatingLabelInput.js
  src/login/Login.js
  src/profile/Profile.js
Labels: enhancement

#33 Adicionado visualização do perfil
  App.js
  src/components/ButtonComponent.js
  src/login/Login.js
  src/profile/Profile.js
  src/profile/ProfileHeader.js
  src/styles/GeneralStyle.js
  src/styles/LoginScreenStyle.js
  src/styles/ProfileStyle.js
Labels: Feature, US

#37 Corrige mapeamento e instalação de dependências
  docker-compose.yml
Labels: bug, enhancement

#40 Login Front End
  .gitignore
  package.json
  src/login/Login.js
  src/profile/Profile.js
  yarn.lock
Labels: enhancement
